-- Swipe file posts sent to the Biolinx content library (docs/integrations/biolinx-content-api.md).
-- One row per version: a declined post keeps its row and the regenerated one points back via parent_id.
CREATE TABLE IF NOT EXISTS swipe_posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  external_id VARCHAR(120) NOT NULL,
  parent_id INT NULL,
  version INT NOT NULL DEFAULT 1,
  source_lead_id INT NULL,
  source_post_url VARCHAR(500) NULL,
  source_platform VARCHAR(16) NULL,
  source_stats JSON NULL,
  niche VARCHAR(40) NULL,
  biolinx_niche VARCHAR(16) NOT NULL,
  platform VARCHAR(16) NOT NULL,
  format VARCHAR(12) NOT NULL,
  hook_type VARCHAR(16) NULL,
  angle VARCHAR(255) NULL,
  hook VARCHAR(120) NOT NULL,
  caption TEXT NOT NULL,
  hashtags JSON NULL,
  image_text VARCHAR(120) NULL,
  image_brief TEXT NULL,
  image_url VARCHAR(1000) NULL,
  reviewer_feedback TEXT NULL,
  preflight JSON NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'draft',
  decided_by_user_id INT NULL,
  decided_at DATETIME NULL,
  sent_at DATETIME NULL,
  biolinx_id INT NULL,
  biolinx_status VARCHAR(16) NULL,
  media_url VARCHAR(1000) NULL,
  media_id INT NULL,
  image_check VARCHAR(12) NULL,
  issues JSON NULL,
  reasons JSON NULL,
  added JSON NULL,
  error TEXT NULL,
  last_event VARCHAR(24) NULL,
  last_event_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY swipe_external_id (external_id),
  KEY swipe_status (status),
  KEY swipe_source_post (source_post_url(191))
);
